# standard jekyll configuration

name: kiki
url: http://kiki.microcai.org
description: kiki 的 blog

permalink: date
pygments: true
markdown: rdiscount
baseurl: /

source: .
destination: ./_site
plugins: ./_plugins

# configuration required for some pages

domain: microcai.org
title: 丫头开在夏天里
author: kiki
email: kiki.caicai@gmail.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
   username: kikidong

disqus:
   id: drcai
